[package]
name = "nosmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.asm]
inherits = "release"
opt-level = "z" # Disables most inlines
strip = "none"
debug = "full"
